### ISSUE TITLE
a way to check a variable is an observable

### ISSUE THREAD

**Issue by nakosung** [dominictarr/observable#13]
Hello! I've played with observable for several days to find out that it is a really amazing framework to build a great app with. 

To add an elegance of seamlessness between observables and normal values, it is needed to check a var is an observable.

```
get = (x) -> if is_observable(x) then x() else x 
```

what is the recommended way to check an var is an observable? 

In hyperscript, if a var is a function, the var is assumed as an observable, but we can store a function into a observable so this doesn't seem to be good.

**Comment by its-dibo** [comment]
rxjs now has a function isObservable

or you can implement it yourself like so:
```
function isObservable(obj: any): obj is Observable<unknown> {
  // The !! is to ensure that this publicly exposed function returns
  // `false` if something like `null` or `0` is passed.
  return !!obj && (obj instanceof Observable || (isFunction(obj.lift) && isFunction(obj.subscribe)));
}
```
