### ISSUE TITLE
should the eventhandler be called when it's registred?

### ISSUE THREAD

**Issue by werty1st** [dominictarr/observable#17]
this is my workaround because i dont want the storage function to be called 

const o = require('observable'); 
const persist = o();

let lastnews = storage.getItemSync("lastnews")
persist( lastnews ); //set the observable to the loaded value

let firstrun = true;
persist( (value) =>{
    if(!firstrun){
        storage.setItemSync("lastnews",value);
        log.info("settings saved",value);
    }
    firstrun=false;
}); //=> this would call storage.setItemSync("lastnews",value) with the previously set value which is undesirable

**Comment by dominictarr** [comment]
calling immediatly is necessary to make observables compose - you can pass an observable to another observable, etc.
I think the simple solution, for this case, is to check whether the new value is different from the current value before calling `setTimeSync`
